### ISSUE TITLE
DB ssl setup

### ISSUE THREAD

**Issue by productdevbook** [easypanel-io/community#14]
Let's Encrypt certificate to secure connections

https://www.vultr.com/docs/use-ssl-encryption-with-postgresql-on-ubuntu-20-04/

**Comment by deiucanta** [comment]
https://community.traefik.io/t/running-multiple-databases-via-traefik-and-accessing-the-databases-from-the-host-machine/11369/2

Based on this answer, I see Traefik will not allow us to have multiple database instances routed through the same port.

Another option would be to provision the SSL certificates directly in Easypanel. Considering the current state of the project, this is not a priority.
