### ISSUE TITLE
Weird re-attribution of repo

### ISSUE THREAD

**Issue by ijpatricio** [easypanel-io/community#15]
Ok, I will have to repeat again to confirm, but I'm 99.999% sure this is what happened.

I had:  
- service: blog
  repo: owner/repo1

I tried to just change repo to owner/repo2. it gave the error message toast: "can't find github repo" (something similar)

So, I thought: destroy service, recreate, so I did, and then I restarted:
- service: blog
  repo: owner/repo2

-> same error message

But all was good.. I tried something else: repo2, but in a whole new service

- service: somethingelse
  repo: owner/repo2

It worked.

**Comment by deiucanta** [comment]
The error message was too ambiguous before. It gave "can't find github repo" for other non-related reasons. For example, if the branch didn't exist it gave the same error. Now it should be more explicit.

If you encounter this bug again, please reopen the issue.
