### ISSUE TITLE
Very small shell size

### ISSUE THREAD

**Issue by ijpatricio** [easypanel-io/community#16]
Following picture is in a 1920 pixel wide viewport, and it feels very small.
Following the golden ratio, (1.6), I would recommend it to be 1200px wide.  (1200 * 1.6 = 1920)

![image](https://user-images.githubusercontent.com/26031459/164836025-294a5f78-9690-4efe-aae2-661b54e9dd61.png)

**Comment by ijpatricio** [comment]
While we're at it...

If Launcher is the thing to use when used Buildpacks, then it's better to be informative about it

**Comment by deiucanta** [comment]
I made it wider for now and I want to make it resizable in the future.
