### ISSUE TITLE
UI misleading port in use

### ISSUE THREAD

**Issue by ijpatricio** [easypanel-io/community#18]
I changed a mysql port mapping.

In my opinion, the MySQL template should also indicate that the container is serving on 3306.

It should be clear that other containers in the same docker network can connect through <container>:3306.

This is because we might want to block via firewall the port on host. This way, containers can use directly, and developers that want to connect directly to database can do that, using the mapped port only when firewall allows it.

![image](https://user-images.githubusercontent.com/26031459/164836503-92d99964-1b12-4637-a705-0f495c75aa0b.png)

**Comment by deiucanta** [comment]
A DB service is only available inside the server at the beginning. The other services are able to connect to it but no one from outside can connect.

If you want to connect from outside, you need to expose the DB on a specific port on the host server (IP).

- if DB is not exposed, the host will be `[project-name]_[service-name]:3306`
- if DB is exposed, the host will be `[host-ip]:[exposed-port]`

How can I explain this better? Maybe I should have a toggle/switch that clearly shows the two modes (exposed or not exposed)

**Comment by ijpatricio** [comment]
The misleading I'm talking about is that there are two ports possible, in the picture

You can connect to the <host>:3310, or to the <container>:3306

Say, in a node app running in a container, you wouldn't have to go there and change to 3310.
This is only relevant to connecting from outside the VPS.

Hence, I was expecting to see information clearly about the service availability ports, both of them (when exposed)

**Comment by deiucanta** [comment]
Fixed with an improved UI
