### ISSUE TITLE
Config File / Docker Compose

### ISSUE THREAD

**Issue by ravenbroetzmann** [easypanel-io/community#23]
find a docker-compose in repo and build services

**Comment by deiucanta** [comment]
You basically want to manage an Easypanel project from a file instead of the UI?

Do you need the actual Docker Compose syntax or any syntax will work?

**Comment by ijpatricio** [comment]
I second this.

It's not my post, but I would say Docker Compose syntax, as I wouldn't have to transform...

I can't even see, why would it be better to not having Compose Syntax?

**Comment by ravenbroetzmann** [comment]
A docker-compose would be absolutely amazing but a custom config should do their job too..

I don't know but to implement all functionality of a docker compose could be overwhelming...

**Comment by deiucanta** [comment]
Unfortunately, it's not that simple.

There are some things that Easypanel supports that Docker Compose doesn't, and vice-versa. For example, exposing the services on a specific domain. If you want to do that in `docker-compose.yml` you need to add the proper Traefik labels manually.

![image](https://user-images.githubusercontent.com/2116280/165165157-8a5027f2-c4f3-40b4-bb5c-2d56d8f71996.png)

If we use the format of `docker-compose.yml` we will have to disable the things which are only in Compose (area 1 in the diagram) and add the things which are only in Easypanel (area 3 in the diagram)

**Comment by ravenbroetzmann** [comment]
for me it does not matter because, i have a docker-compose.dev.yml and docker-compose.prod.yml so to change the prod to easypanel-deploy.yml is not that bad if the syntaxs stays...

**Comment by deiucanta** [comment]
You scratched your own itch! https://github.com/ravenbroetzmann/compose-to-easypanel
