### ISSUE TITLE
Callback URL after deploy

### ISSUE THREAD

**Issue by ijpatricio** [easypanel-io/community#28]
After a deploy, easypanel can send a POST request to a webhook.

In "Project - Service - General", after Webhook:   "After-Deploy Callback URL"

Textfield for URL (instructions or reminder to put slack or discord webhook, for example)
Payload Info: {status, host, project, service}
It can be only after "Auto-deploy", or every deploy (checkbox)

**Comment by deiucanta** [comment]
Moved here: https://feedback.easypanel.io/feature-requests/p/call-url-after-deploy
