### ISSUE TITLE
Support Gitlab and Bitbucket

### ISSUE THREAD

**Issue by deiucanta** [easypanel-io/community#32]

**Comment by Ponkhy** [comment]
And Gitea would be lovely too :)

**Comment by deiucanta** [comment]
Moved here:

- https://feedback.easypanel.io/feature-requests/p/support-gitlab
- https://feedback.easypanel.io/feature-requests/p/support-bitbucket
- https://feedback.easypanel.io/feature-requests/p/support-gitea
