### ISSUE TITLE
Proxy Reverse Manager

### ISSUE THREAD

**Issue by ravenbroetzmann** [easypanel-io/community#33]
if would be nice to have a proxy manager tab build in like the nginx proxy manager where you can map urls to ports, create and renew ssl certs an all the good stuff...

but i think this is not so important right now but maybe later...

**Comment by deiucanta** [comment]
Can you list the features that you have in nginx proxy manager and you'd like to have in Easypanel?

I prefer to keep the settings under each server, not in a separate global tab. However, I'm open to ideas!

**Comment by ravenbroetzmann** [comment]
The only feature left I maybe need:

- basic auth 
- redirection
- create and manage let's encrypt certificates 

Having everything organized in the service tabs is a better idea

**Comment by deiucanta** [comment]
Moved here:

- https://feedback.easypanel.io/feature-requests/p/redirects
- https://feedback.easypanel.io/feature-requests/p/manually-renew-ssl-certificates
