### ISSUE TITLE
Add Mariadb

### ISSUE THREAD

**Issue by jimcru21** [easypanel-io/community#39]

**Comment by deiucanta** [comment]
I just released a new version which allows you to specify the Docker image for a DB service. You could create a MySQL service and type `mariadb:latest` in the `image` field.

**Comment by productdevbook** [comment]
how to nginx with used mariadb ? Because now ` Apache/2.4.53 (Debian) ` used

**Comment by deiucanta** [comment]
> how to nginx with used mariadb ? Because now `Apache/2.4.53 (Debian)` used

I'm sorry but I don't understand what you mean

**Comment by deiucanta** [comment]
MariaDB is now a core service
