### ISSUE TITLE
Set domain for admin UI

### ISSUE THREAD

**Issue by reyemtm** [easypanel-io/community#40]
Awesome app! My caprover kept crashing so this project looks like a promising replacement.

Is there a way to set a domain for the base admin UI? Since the app already has the ability to create and use SSL domains it would seem like this would be possible, though I have not looked into the code and didn't see anywhere in the settings to add this.

**Comment by Ponkhy** [comment]
Hey, it's already on the [Roadmap #12](https://github.com/orgs/easypanel-io/projects/1/views/1) and will probably be added in the near future!

**Comment by reyemtm** [comment]
awesome, thanks!

**Comment by deiucanta** [comment]
Release in 1.5.3
