### ISSUE TITLE
Not possible to start a MongoDB Service

### ISSUE THREAD

**Issue by Ponkhy** [easypanel-io/community#41]
It is not possible to start a MongoDB Service, you will receive this error:

![Error](https://i.imgur.com/0KD9vtj.png)

**Comment by deiucanta** [comment]
Here is an explanation for the issue you're facing. 

https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

I could make v4 the default version, but it will hurt people who have the proper CPU. Maybe I should add an option so you can choose which version you want to use (v4 or v5).

What do you think?

**Comment by Ponkhy** [comment]
Yea to have the option would be great!
The same would also be great for MySQL.

**Comment by deiucanta** [comment]
Here you go. Each DB service has an `image` field now.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2116280/167616824-a8131340-c06a-4cef-88ec-7f81e8880c46.png">
