### ISSUE TITLE
Error: "Cannot access repository" when setting up an app

### ISSUE THREAD

**Issue by valen20Chx** [easypanel-io/community#49]
Hi, I'm trying to setup easypanel on my server and I'm getting an error when I try to save the "source". (see img)

![image](https://user-images.githubusercontent.com/33943799/169675596-1c2f6093-35b2-4179-ad77-ca8217127252.png)
(obviously I use the correct names for the github owner and repo, I also tried other repos)

It's running on a ubuntu server hosted by Vultr.

Has anyone experienced this, am I missing some configuration ?

The network tab in the web browser doesnt have any additional info.

Things I tried:

- Recreating a github token
- Other repo
- Check logs of the docker containers
- Check that the containers has access to the internet (`curl github.com` from inside the easypanel container)
- Move from default server type to easypanel template on vultr

**Comment by Ponkhy** [comment]
Hey, just to make sure, it should look something like this for you too, right?

![Example](https://i.imgur.com/J9fFzFa.png)

**Comment by valen20Chx** [comment]
@Ponkhy Yes,

![image](https://user-images.githubusercontent.com/33943799/169703426-d38821a2-fdfb-417e-8b4f-765ba8878601.png)

**Comment by valen20Chx** [comment]
Can I retrieve some logs to get a more descriptive assessment of the error ?

**Comment by deiucanta** [comment]
This seems very improbable, but I don't know what else could be. Can you check that the account you issued the token for, has access to the repo you're trying to connect?

> Can I retrieve some logs to get a more descriptive assessment of the error?

You could run `docker service logs easypanel` but I doubt you will find additional info there.

**Comment by valen20Chx** [comment]
> Can you check that the account you issued the token for, has access to the repo you're trying to connect?
Yea it's my own account and repo, so it should be okay.

The only output I get from the logs of the easypanel container is :
`> Ready on http://localhost:3000`

**Comment by deiucanta** [comment]
Try to connect to a public repository and let me know if it works.

**Comment by valen20Chx** [comment]
@deiucanta I got it to work, it was my mistake and lack of attention.

I just picked the wrong branch, by default it's "main". Using the correct one fixed it.

Thanks for your help
