### ISSUE TITLE
File Backups

### ISSUE THREAD

**Issue by marktopper** [easypanel-io/community#51]
It would be cool to have files regularly backup to a remote source, like Dropbox or S3.

Like I would define a path where all the uploaded user resources would be located, then it would be able to backup and restore that location, other files would be in Git so no reason to force using the project path for it.

**Comment by deiucanta** [comment]
Added 3 templates you can use for backups. Duplicati is a general-purpose backup solution and has many remote options.

- https://easypanel.io/docs/templates/duplicati
- https://easypanel.io/docs/templates/mysql-backup
- https://easypanel.io/docs/templates/postgres-backup
