### ISSUE TITLE
Add "chown" property to volumes (for templates)

### ISSUE THREAD

**Issue by deiucanta** [easypanel-io/community#57]
Needed here: https://github.com/easypanel-io/templates/pull/64

**Comment by deiucanta** [comment]
The last release (1.7.3) changes the way volumes work. This "chown" might not be needed. 

@marktopper Would you mind testing your template on the latest Easypanel?

**Comment by marktopper** [comment]
I can confirm that this solves the issue @deiucanta.
Thank you very much.
