### ISSUE TITLE
Add support for wildcard LE certificates

### ISSUE THREAD

**Issue by jzaplet** [easypanel-io/community#61]
Hi, I really appreciate your great work. This is the tool what I've been looking for a years.
But is it possible to add support for wildcard Let's Encrypt certificates?

![Screenshot 2022-07-18 at 16 37 15](https://user-images.githubusercontent.com/4992367/179535857-26d1464f-04ec-4fe8-ab98-257dc9ad8003.png)

**Comment by deiucanta** [comment]
Moved here: https://feedback.easypanel.io/feature-requests/p/wildcard-ssl-certificates
