### ISSUE TITLE
better env variables editing

### ISSUE THREAD

**Issue by ravenbroetzmann** [easypanel-io/community#62]
a better interface for editing env variables would be nice.
for example for each env variable one input for `key` and one input for `value`.
similar to the `ports` section.

but syntax highlighting and better spacing would be enough too

**Comment by deiucanta** [comment]
The last version of Easypanel uses a monospace font so it should look better now.

I always find it difficult to work with env editors that have multiple input fields. Editing variables in Netlify, for example, seems very tedious to me.

Do you like it? Do you prefer it? What about having comments?

![image](https://user-images.githubusercontent.com/2116280/182501160-890b3f2e-c234-493e-a9cf-44f9c639d984.png)

**Comment by ravenbroetzmann** [comment]
I personally prefer the view of the Netlify Way but you're right, you can better work with a text field.

So maybe more spacing between the lines and syntax highlighting would be the best way to make it more clearer to work with.

So maybe you split each line by  `=` and then you make the first index (the env key) bold and with a nice color

**Comment by deiucanta** [comment]
Moved here: https://feedback.easypanel.io/feature-requests/p/better-environment-variables-editing
