### ISSUE TITLE
Restrict access from public ip

### ISSUE THREAD

**Issue by shc623** [easypanel-io/community#64]
If have this option for security reason it will be nice.

**Comment by deiucanta** [comment]
My plan is to give each server a subdomain like `[ip].easypanel.host`. What do you think?

Also, what are your security concerns right now? Do you want to avoid the bots scanning the internet?

**Comment by shc623** [comment]
I thought because admin panel has sensitive functions like console. I felt want to isolate it from any public access

**Comment by deiucanta** [comment]
Moved here: https://feedback.easypanel.io/feature-requests/p/restrict-access-from-public-ip
