### ISSUE TITLE
Add Project Scoped Env Vars

### ISSUE THREAD

**Issue by ravenbroetzmann** [easypanel-io/community#65]
Often you use the same variables in multiple services (e.g. database url)

It would be awesome if easypanel would detect all env vars used in one project an would display them in a new tab.

So you would have `Projects` -> `<Project Name>` -> `Services` and `Project ENV`

That you are able to edit one variable used in multiple services at once

**Comment by deiucanta** [comment]
Moved here: https://feedback.easypanel.io/feature-requests/p/project-scoped-environment-variables
