### ISSUE TITLE
Native Backup Tab

### ISSUE THREAD

**Issue by ravenbroetzmann** [easypanel-io/community#67]
I now you already are planing it but I just share my ideas.

Each Service should have a tab called `backup`

The backup tab shows all recent backups and has the ability to restore them. And of course a big button to create new backups

**Backup For App Service:**

- backup the Schema file to easily recreate the service
- backup the whole service dir 

**Backup Database**
- backup the Schema file to easily recreate the service
- backup the whole data dir 

**Backup Projects** 
Backup the whole project would be nice to 

- backup the project Schema 
- backup the project dir

The question is where to store the backups, on the same server, local or remote or both

**Comment by deiucanta** [comment]
Moved here: https://feedback.easypanel.io/feature-requests/p/native-backups
