### ISSUE TITLE
Disabling Serve on IP Address and Port (not working) (v1.10.2)

### ISSUE THREAD

**Issue by heykripa** [easypanel-io/community#73]
Feature is working good in the server 1 which was upgraded from v1.10.1 to v.1.10.2 today (directly from dashboard navigation).

Built a new server (server 2) for another project and pulled easypanel latest with one-click sh. It directly install v1.10.2 and server on ip address feature is not working. Tried at least 6 times, removed easypanel from docker, reinstalled it, and rebuilt server for couple of times, and its not yet working. Still servers on IP address.

![Screenshot 2022-09-08 at 11 13 27 PM](https://user-images.githubusercontent.com/21086957/189191248-7fc99591-2eaa-437f-aa84-260249e53867.png)
![Screenshot 2022-09-08 at 11 16 03 PM](https://user-images.githubusercontent.com/21086957/189191269-d1fd32b9-ea72-4bb5-99ca-f3d661f6d2e9.png)

**Comment by deiucanta** [comment]
There are now 3 ways to access Easypanel

1. `http://ip:3000` (always enabled, used as a backup in case the reverse proxy fails)
2. `https://ip` (you can enable/disable it in settings: Server on IP Address)
3. `https://custom-domain` (you can customize in settings)

If you disable the switch "Server on IP", only the 2nd way will be disabled, the 1st one will still work.

Is this the behaviour you're experiencing?

**Comment by heykripa** [comment]
Yes @deiucanta. I'm experiencing the 1st behaviour. My first server apps are showing like this. (Seems good)
But the 2nd new server deployed the latest version of easypanel directly makes port to open.

- On 1st server I can now only able to access via domain `https://custom-domain`
- On 2nd server I can access via method 1, 2 & 3 (`http://ip:3000` `http://ip` `https://custom-domain`)

![image](https://user-images.githubusercontent.com/21086957/189210495-89afd6b9-558d-4015-be2c-95f8d05a0e81.png)

**Comment by deiucanta** [comment]
- 1st way cannot be disabled. It's a feature, not a bug.
- 2st way can be disabled. When you disable it will give you a 404 page (screenshot below).
- 3rd way can be disabled. Just remove the custom domain.

![image](https://user-images.githubusercontent.com/2116280/189214291-d68bef58-5f59-4eb6-9bca-a6f3a90499ac.png)

Please let me know if you're experiencing a bug or you want it to work differently.

**Comment by heykripa** [comment]
As per my understanding..

- 1st way `http:ip:3000` is a feature and not a bug. (which I wish to block at any cost, and I believe it can be done through traefik / ufw). (please correct me if i'm wrong)
- 2nd way is already disabled and I like it. Thanks for this block.
- 3rd way is way more convenient and protective feature. I realllllly like it @deiucanta.

**Comment by deiucanta** [comment]
Awesome! You can block port 3000 using ufw.

**Comment by heykripa** [comment]
After updating 1st server from `v1.10.2` to `v1.10.3`, the null value turned into ip address. So, what I thought as a feature was actually a bug and it's fixed now on your latest push. And what I thought as a bug is a actually a feature. Sorry for the long convo.. ;)

You're doing it Awesome!!!


![image](https://user-images.githubusercontent.com/21086957/189225115-35ca8f65-1866-4981-866b-cdb4b5798ede.png)
<img width="604" alt="Screenshot 2022-09-09 at 2 31 47 AM" src="https://user-images.githubusercontent.com/21086957/189225356-00cb9082-cdf2-4c5c-a04a-171ec2fca8eb.png">

**Comment by deiucanta** [comment]
No worries. Everything makes sense now! :)
