### ISSUE TITLE
Uninstall this

### ISSUE THREAD

**Issue by seracoder** [easypanel-io/community#75]
I installed easypanel via the one line command and now cannot remove it from docker, 
I tried to stop the container and remove it but it just keeps replicating again itself.

**Comment by SuperManito** [comment]
## OneKey Tutorial - Uninstall/Remove

### 1. Delete Service

```bash
docker service rm "$(docker service ls | grep -E "easypanel|error-pages|traefik" | awk '{print $1}' | tr -s '\n' ' ')"
```

### 2. Delete Images
```bash
docker rmi "$(docker images | grep -E "easypanel|error-pages|traefik" | awk '{print $1}' | tr -s '\n' ' ')"
```

### 3. Delete Local Files
```bash
rm -rf /etc/easypanel
```
