### ISSUE TITLE
PostgreSQL version 15 is not compatible with version 16.0 (Debian 16.0-1.pgdg120+1).

### ISSUE THREAD

**Issue by KLISCHE-HW** [easypanel-io/community#88]
I have installed easypanel.io in an Ubuntu 22.04 enviroment and got suddenly this error message:
The data directory was initialized by PostgreSQL version 15, which is not compatible with this version 16.0 (Debian 16.0-1.pgdg120+1).

**Comment by deiucanta** [comment]
Just pushed a new release where you can configure the docker image for a database service. Please update to 1.23.2 and change your postgres image to `postgres:15`.

Sorry for the inconvenience!
